name: Update GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          # Docs have to be built before the demo app
          npm ci
          cd demo && npm ci && cd -
          npm run build:docs
          npm run build:demo
      - name: Upload to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
